version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-app
    ports:
      - "443:443"
    depends_on:
      - fastapi
